// 由迁移对应的数据库结构生成，请运行 npm run db:types 更新。
type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
export type Database = {
  edm: {
    Tables: {
      activity_logs: {
        Row: {
          id: string;
          workspace_id: string;
          actor_id: string | null;
          actor_name: string;
          actor_role: string;
          action: string;
          target_type: string;
          target_id: string | null;
          target_label: string;
          metadata: Json;
          dedupe_key: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          actor_id?: string | null;
          actor_name: string;
          actor_role: string;
          action: string;
          target_type: string;
          target_id?: string | null;
          target_label?: string;
          metadata?: Json;
          dedupe_key?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          actor_id?: string | null;
          actor_name?: string;
          actor_role?: string;
          action?: string;
          target_type?: string;
          target_id?: string | null;
          target_label?: string;
          metadata?: Json;
          dedupe_key?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      campaign_delivery_attempts: {
        Row: {
          id: string;
          workspace_id: string;
          run_id: string;
          task_id: string;
          attempt_number: number;
          credential_version: number;
          status: string;
          provider_call_started_at: string;
          completed_at: string | null;
          provider_request_id: string | null;
          provider_env_id: string | null;
          provider_message_id: string | null;
          error_category: string | null;
          error_code: string | null;
          resolved_as: string | null;
          resolved_by: string | null;
          resolved_at: string | null;
          resolution_note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          run_id: string;
          task_id: string;
          attempt_number: number;
          credential_version: number;
          status?: string;
          provider_call_started_at?: string;
          completed_at?: string | null;
          provider_request_id?: string | null;
          provider_env_id?: string | null;
          provider_message_id?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          resolved_as?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          run_id?: string;
          task_id?: string;
          attempt_number?: number;
          credential_version?: number;
          status?: string;
          provider_call_started_at?: string;
          completed_at?: string | null;
          provider_request_id?: string | null;
          provider_env_id?: string | null;
          provider_message_id?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          resolved_as?: string | null;
          resolved_by?: string | null;
          resolved_at?: string | null;
          resolution_note?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      campaign_delivery_events: {
        Row: {
          id: string;
          workspace_id: string;
          channel_id: string;
          run_id: string | null;
          task_id: string | null;
          attempt_id: string | null;
          subscription_event_id: string | null;
          provider: string;
          provider_event_id: string;
          provider_event_type: string;
          event_type: string;
          provider_env_id: string | null;
          provider_message_id: string | null;
          sender_address: string | null;
          recipient_email: string;
          provider_status: string | null;
          error_code: string | null;
          failure_type: string | null;
          occurred_at: string;
          provider_sent_at: string | null;
          received_at: string;
          matched_at: string | null;
          processed_at: string | null;
          processing_status: string;
          match_attempts: number;
          next_match_at: string;
          last_error_code: string | null;
          payload_sha256: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          channel_id: string;
          run_id?: string | null;
          task_id?: string | null;
          attempt_id?: string | null;
          subscription_event_id?: string | null;
          provider?: string;
          provider_event_id: string;
          provider_event_type: string;
          event_type: string;
          provider_env_id?: string | null;
          provider_message_id?: string | null;
          sender_address?: string | null;
          recipient_email: string;
          provider_status?: string | null;
          error_code?: string | null;
          failure_type?: string | null;
          occurred_at: string;
          provider_sent_at?: string | null;
          received_at?: string;
          matched_at?: string | null;
          processed_at?: string | null;
          processing_status?: string;
          match_attempts?: number;
          next_match_at?: string;
          last_error_code?: string | null;
          payload_sha256: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          channel_id?: string;
          run_id?: string | null;
          task_id?: string | null;
          attempt_id?: string | null;
          subscription_event_id?: string | null;
          provider?: string;
          provider_event_id?: string;
          provider_event_type?: string;
          event_type?: string;
          provider_env_id?: string | null;
          provider_message_id?: string | null;
          sender_address?: string | null;
          recipient_email?: string;
          provider_status?: string | null;
          error_code?: string | null;
          failure_type?: string | null;
          occurred_at?: string;
          provider_sent_at?: string | null;
          received_at?: string;
          matched_at?: string | null;
          processed_at?: string | null;
          processing_status?: string;
          match_attempts?: number;
          next_match_at?: string;
          last_error_code?: string | null;
          payload_sha256?: string;
        };
        Relationships: [];
      };
      campaign_delivery_runs: {
        Row: {
          id: string;
          workspace_id: string;
          campaign_id: string;
          snapshot_id: string;
          channel_id: string;
          idempotency_key: string;
          status: string;
          region: string;
          sender_address: string;
          sender_alias: string;
          reply_to_address: string | null;
          channel_version: number;
          credential_version: number;
          recipient_count: number;
          started_by: string;
          started_at: string;
          paused_at: string | null;
          pause_reason: string | null;
          resumed_at: string | null;
          aborted_at: string | null;
          completed_at: string | null;
          updated_at: string;
          version: number;
          sender_workspace_name: string;
          sender_mailing_address: string;
          tracking_enabled: boolean;
          tracking_tag_name: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          campaign_id: string;
          snapshot_id: string;
          channel_id: string;
          idempotency_key: string;
          status?: string;
          region: string;
          sender_address: string;
          sender_alias: string;
          reply_to_address?: string | null;
          channel_version: number;
          credential_version: number;
          recipient_count: number;
          started_by: string;
          started_at?: string;
          paused_at?: string | null;
          pause_reason?: string | null;
          resumed_at?: string | null;
          aborted_at?: string | null;
          completed_at?: string | null;
          updated_at?: string;
          version?: number;
          sender_workspace_name: string;
          sender_mailing_address: string;
          tracking_enabled?: boolean;
          tracking_tag_name?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          campaign_id?: string;
          snapshot_id?: string;
          channel_id?: string;
          idempotency_key?: string;
          status?: string;
          region?: string;
          sender_address?: string;
          sender_alias?: string;
          reply_to_address?: string | null;
          channel_version?: number;
          credential_version?: number;
          recipient_count?: number;
          started_by?: string;
          started_at?: string;
          paused_at?: string | null;
          pause_reason?: string | null;
          resumed_at?: string | null;
          aborted_at?: string | null;
          completed_at?: string | null;
          updated_at?: string;
          version?: number;
          sender_workspace_name?: string;
          sender_mailing_address?: string;
          tracking_enabled?: boolean;
          tracking_tag_name?: string | null;
        };
        Relationships: [];
      };
      campaign_delivery_tasks: {
        Row: {
          id: string;
          workspace_id: string;
          run_id: string;
          recipient_snapshot_id: string;
          position: number;
          status: string;
          attempt_count: number;
          next_attempt_at: string;
          lease_token: string | null;
          lease_expires_at: string | null;
          active_attempt_id: string | null;
          skip_reason: string | null;
          error_category: string | null;
          error_code: string | null;
          accepted_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
          version: number;
          delivery_status: string;
          delivery_status_at: string | null;
          feedback_status: string;
          feedback_status_at: string | null;
          provider_message_id: string | null;
          first_opened_at: string | null;
          first_clicked_at: string | null;
          last_event_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          run_id: string;
          recipient_snapshot_id: string;
          position: number;
          status?: string;
          attempt_count?: number;
          next_attempt_at?: string;
          lease_token?: string | null;
          lease_expires_at?: string | null;
          active_attempt_id?: string | null;
          skip_reason?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          accepted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
          delivery_status?: string;
          delivery_status_at?: string | null;
          feedback_status?: string;
          feedback_status_at?: string | null;
          provider_message_id?: string | null;
          first_opened_at?: string | null;
          first_clicked_at?: string | null;
          last_event_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          run_id?: string;
          recipient_snapshot_id?: string;
          position?: number;
          status?: string;
          attempt_count?: number;
          next_attempt_at?: string;
          lease_token?: string | null;
          lease_expires_at?: string | null;
          active_attempt_id?: string | null;
          skip_reason?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          accepted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
          delivery_status?: string;
          delivery_status_at?: string | null;
          feedback_status?: string;
          feedback_status_at?: string | null;
          provider_message_id?: string | null;
          first_opened_at?: string | null;
          first_clicked_at?: string | null;
          last_event_at?: string | null;
        };
        Relationships: [];
      };
      campaign_recipient_snapshots: {
        Row: {
          id: string;
          workspace_id: string;
          snapshot_id: string;
          position: number;
          contact_id: string;
          email: string;
          name: string;
          subject: string;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          snapshot_id: string;
          position: number;
          contact_id: string;
          email: string;
          name: string;
          subject: string;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          snapshot_id?: string;
          position?: number;
          contact_id?: string;
          email?: string;
          name?: string;
          subject?: string;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      campaign_snapshots: {
        Row: {
          id: string;
          workspace_id: string;
          campaign_id: string;
          campaign_name: string;
          template_id: string;
          template_name: string;
          template_subject: string;
          template_body: string;
          template_version: number;
          audience_type: string;
          tag_id: string | null;
          tag_name: string | null;
          variables: Json;
          audience_count: number;
          recipient_count: number;
          excluded_archived_count: number;
          excluded_suppressed_count: number;
          excluded_not_subscribed_count: number;
          confirmed_by: string;
          confirmed_by_name: string;
          confirmed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          campaign_id: string;
          campaign_name: string;
          template_id: string;
          template_name: string;
          template_subject: string;
          template_body: string;
          template_version: number;
          audience_type: string;
          tag_id?: string | null;
          tag_name?: string | null;
          variables: Json;
          audience_count: number;
          recipient_count: number;
          excluded_archived_count: number;
          excluded_suppressed_count: number;
          excluded_not_subscribed_count: number;
          confirmed_by: string;
          confirmed_by_name: string;
          confirmed_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          campaign_id?: string;
          campaign_name?: string;
          template_id?: string;
          template_name?: string;
          template_subject?: string;
          template_body?: string;
          template_version?: number;
          audience_type?: string;
          tag_id?: string | null;
          tag_name?: string | null;
          variables?: Json;
          audience_count?: number;
          recipient_count?: number;
          excluded_archived_count?: number;
          excluded_suppressed_count?: number;
          excluded_not_subscribed_count?: number;
          confirmed_by?: string;
          confirmed_by_name?: string;
          confirmed_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          template_id: string;
          audience_type: string;
          tag_id: string | null;
          variables: Json;
          status: string;
          archived_at: string | null;
          created_by: string;
          updated_by: string;
          created_at: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          template_id: string;
          audience_type: string;
          tag_id?: string | null;
          variables?: Json;
          status?: string;
          archived_at?: string | null;
          created_by: string;
          updated_by: string;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          template_id?: string;
          audience_type?: string;
          tag_id?: string | null;
          variables?: Json;
          status?: string;
          archived_at?: string | null;
          created_by?: string;
          updated_by?: string;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      contact_import_rows: {
        Row: {
          import_id: string;
          workspace_id: string;
          item_no: number;
          source_rows: string;
          email: string;
          name: string;
          tags: string;
          requested_status: string;
          consent_source: string | null;
          consent_note: string | null;
          consent_at: string | null;
          preview_result: string;
          result: string;
          message: string;
          contact_id: string | null;
          processed_at: string | null;
        };
        Insert: {
          import_id: string;
          workspace_id: string;
          item_no: number;
          source_rows: string;
          email: string;
          name?: string;
          tags?: string;
          requested_status: string;
          consent_source?: string | null;
          consent_note?: string | null;
          consent_at?: string | null;
          preview_result: string;
          result?: string;
          message?: string;
          contact_id?: string | null;
          processed_at?: string | null;
        };
        Update: {
          import_id?: string;
          workspace_id?: string;
          item_no?: number;
          source_rows?: string;
          email?: string;
          name?: string;
          tags?: string;
          requested_status?: string;
          consent_source?: string | null;
          consent_note?: string | null;
          consent_at?: string | null;
          preview_result?: string;
          result?: string;
          message?: string;
          contact_id?: string | null;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      contact_imports: {
        Row: {
          id: string;
          workspace_id: string;
          source_type: string;
          source_name: string;
          consent_declared: boolean;
          consent_source: string | null;
          consent_note: string | null;
          consent_at: string | null;
          status: string;
          total_source_rows: number;
          total_groups: number;
          processed_groups: number;
          summary: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          source_type: string;
          source_name: string;
          consent_declared?: boolean;
          consent_source?: string | null;
          consent_note?: string | null;
          consent_at?: string | null;
          status?: string;
          total_source_rows: number;
          total_groups: number;
          processed_groups?: number;
          summary?: Json;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          source_type?: string;
          source_name?: string;
          consent_declared?: boolean;
          consent_source?: string | null;
          consent_note?: string | null;
          consent_at?: string | null;
          status?: string;
          total_source_rows?: number;
          total_groups?: number;
          processed_groups?: number;
          summary?: Json;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contact_tags: {
        Row: { workspace_id: string; contact_id: string; tag_id: string };
        Insert: { workspace_id: string; contact_id: string; tag_id: string };
        Update: { workspace_id?: string; contact_id?: string; tag_id?: string };
        Relationships: [];
      };
      contacts: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          name: string;
          archived_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          version: number;
          subscription_status: string;
          consent_source: string | null;
          consent_note: string | null;
          consent_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          name?: string;
          archived_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          version?: number;
          subscription_status?: string;
          consent_source?: string | null;
          consent_note?: string | null;
          consent_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          name?: string;
          archived_at?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          version?: number;
          subscription_status?: string;
          consent_source?: string | null;
          consent_note?: string | null;
          consent_at?: string | null;
        };
        Relationships: [];
      };
      delivery_channels: {
        Row: {
          id: string;
          workspace_id: string;
          provider: string;
          status: string;
          region: string;
          sender_domain: string;
          sender_address: string;
          sender_alias: string;
          reply_to_address: string | null;
          access_key_hint: string | null;
          credential_version: number;
          last_verified_at: string | null;
          last_error_code: string | null;
          created_by: string;
          updated_by: string;
          created_at: string;
          updated_at: string;
          disconnected_at: string | null;
          version: number;
          tracking_enabled: boolean;
          tracking_tag_name: string | null;
        };
        Insert: {
          id: string;
          workspace_id: string;
          provider?: string;
          status?: string;
          region: string;
          sender_domain: string;
          sender_address: string;
          sender_alias: string;
          reply_to_address?: string | null;
          access_key_hint?: string | null;
          credential_version?: number;
          last_verified_at?: string | null;
          last_error_code?: string | null;
          created_by: string;
          updated_by: string;
          created_at?: string;
          updated_at?: string;
          disconnected_at?: string | null;
          version?: number;
          tracking_enabled?: boolean;
          tracking_tag_name?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          provider?: string;
          status?: string;
          region?: string;
          sender_domain?: string;
          sender_address?: string;
          sender_alias?: string;
          reply_to_address?: string | null;
          access_key_hint?: string | null;
          credential_version?: number;
          last_verified_at?: string | null;
          last_error_code?: string | null;
          created_by?: string;
          updated_by?: string;
          created_at?: string;
          updated_at?: string;
          disconnected_at?: string | null;
          version?: number;
          tracking_enabled?: boolean;
          tracking_tag_name?: string | null;
        };
        Relationships: [];
      };
      delivery_test_attempts: {
        Row: {
          id: string;
          workspace_id: string;
          channel_id: string;
          idempotency_key: string;
          requested_by: string;
          channel_version: number;
          credential_version: number;
          status: string;
          recipient_hint: string | null;
          provider_request_id: string | null;
          provider_event_id: string | null;
          error_category: string | null;
          error_code: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          workspace_id: string;
          channel_id: string;
          idempotency_key: string;
          requested_by: string;
          channel_version: number;
          credential_version: number;
          status?: string;
          recipient_hint?: string | null;
          provider_request_id?: string | null;
          provider_event_id?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          channel_id?: string;
          idempotency_key?: string;
          requested_by?: string;
          channel_version?: number;
          credential_version?: number;
          status?: string;
          recipient_hint?: string | null;
          provider_request_id?: string | null;
          provider_event_id?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      members: {
        Row: {
          user_id: string;
          status: string;
          display_name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: string;
          display_name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          status?: string;
          display_name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription_events: {
        Row: {
          id: string;
          workspace_id: string;
          contact_id: string | null;
          email: string;
          event_type: string;
          source: string;
          note: string;
          consent_at: string | null;
          import_id: string | null;
          import_item_no: number | null;
          metadata: Json;
          created_by: string | null;
          created_at: string;
          delivery_task_id: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          contact_id?: string | null;
          email: string;
          event_type: string;
          source: string;
          note?: string;
          consent_at?: string | null;
          import_id?: string | null;
          import_item_no?: number | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          delivery_task_id?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          contact_id?: string | null;
          email?: string;
          event_type?: string;
          source?: string;
          note?: string;
          consent_at?: string | null;
          import_id?: string | null;
          import_item_no?: number | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
          delivery_task_id?: string | null;
        };
        Relationships: [];
      };
      suppressions: {
        Row: {
          workspace_id: string;
          email: string;
          reason: string;
          first_event_id: string;
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          email: string;
          reason: string;
          first_event_id: string;
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          email?: string;
          reason?: string;
          first_event_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      tags: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          normalized_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          normalized_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          normalized_name?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      templates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          category: string;
          subject: string;
          body: string;
          default_key: string | null;
          source_template_id: string | null;
          archived_at: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          category: string;
          subject: string;
          body: string;
          default_key?: string | null;
          source_template_id?: string | null;
          archived_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          category?: string;
          subject?: string;
          body?: string;
          default_key?: string | null;
          source_template_id?: string | null;
          archived_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      workspace_invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email_normalized: string;
          role: string;
          token_hash: string;
          token_hint: string;
          status: string;
          expires_at: string;
          invited_by: string;
          accepted_by: string | null;
          accepted_at: string | null;
          revoked_by: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
          version: number;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email_normalized: string;
          role: string;
          token_hash: string;
          token_hint: string;
          status?: string;
          expires_at: string;
          invited_by: string;
          accepted_by?: string | null;
          accepted_at?: string | null;
          revoked_by?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email_normalized?: string;
          role?: string;
          token_hash?: string;
          token_hint?: string;
          status?: string;
          expires_at?: string;
          invited_by?: string;
          accepted_by?: string | null;
          accepted_at?: string | null;
          revoked_by?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      workspace_members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: string;
          status: string;
          joined_at: string;
          removed_at: string | null;
          updated_at: string;
          version: number;
        };
        Insert: {
          workspace_id: string;
          user_id: string;
          role: string;
          status?: string;
          joined_at?: string;
          removed_at?: string | null;
          updated_at?: string;
          version?: number;
        };
        Update: {
          workspace_id?: string;
          user_id?: string;
          role?: string;
          status?: string;
          joined_at?: string;
          removed_at?: string | null;
          updated_at?: string;
          version?: number;
        };
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          type: string;
          plan: string;
          owner_id: string;
          bootstrap_owner_id: string | null;
          mailing_address: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          type?: string;
          plan?: string;
          owner_id: string;
          bootstrap_owner_id?: string | null;
          mailing_address?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          plan?: string;
          owner_id?: string;
          bootstrap_owner_id?: string | null;
          mailing_address?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      initialize_member: { Args: Record<string, never>; Returns: string };
      save_contact: { Args: { payload: Json }; Returns: string };
      archive_contact: { Args: { payload: Json }; Returns: string };
      list_contacts: { Args: { payload: Json }; Returns: Json };
      prepare_contact_import: { Args: { payload: Json }; Returns: Json };
      confirm_contact_import: { Args: { payload: Json }; Returns: Json };
      process_contact_import_batch: { Args: { payload: Json }; Returns: Json };
      get_contact_import: { Args: { payload: Json }; Returns: Json };
      list_contact_imports: { Args: { payload: Json }; Returns: Json };
      export_contact_import: { Args: { payload: Json }; Returns: Json };
      unsubscribe_contact: { Args: { payload: Json }; Returns: string };
      save_template: { Args: { payload: Json }; Returns: string };
      duplicate_template: { Args: { payload: Json }; Returns: string };
      set_template_archived: { Args: { payload: Json }; Returns: string };
      list_templates: { Args: { payload: Json }; Returns: Json };
      list_activity_logs: { Args: { payload: Json }; Returns: Json };
      list_campaigns: { Args: { payload: Json }; Returns: Json };
      get_campaign: { Args: { payload: Json }; Returns: Json };
      get_campaign_preview: { Args: { payload: Json }; Returns: Json };
      confirm_campaign: { Args: { payload: Json }; Returns: Json };
      duplicate_confirmed_campaign: {
        Args: { payload: Json };
        Returns: string;
      };
      get_campaign_export_chunk: { Args: { payload: Json }; Returns: Json };
      save_campaign: { Args: { payload: Json }; Returns: string };
      set_campaign_archived: { Args: { payload: Json }; Returns: string };
      get_campaign_editor_options: { Args: { payload: Json }; Returns: Json };
      get_delivery_channel: { Args: { payload: Json }; Returns: Json };
      save_delivery_channel: { Args: { payload: Json }; Returns: Json };
      disconnect_delivery_channel: { Args: { payload: Json }; Returns: Json };
      configure_delivery_webhook: { Args: { payload: Json }; Returns: Json };
      configure_delivery_tracking: { Args: { payload: Json }; Returns: Json };
      revoke_delivery_webhook: { Args: { payload: Json }; Returns: Json };
      webhook_authorize_delivery_event: {
        Args: { payload: Json };
        Returns: Json;
      };
      webhook_ingest_delivery_event: { Args: { payload: Json }; Returns: Json };
      prepare_delivery_test: { Args: { payload: Json }; Returns: Json };
      get_delivery_test_summary: { Args: { payload: Json }; Returns: Json };
      start_campaign_delivery: { Args: { payload: Json }; Returns: Json };
      set_campaign_delivery_paused: { Args: { payload: Json }; Returns: Json };
      abort_campaign_delivery: { Args: { payload: Json }; Returns: Json };
      get_campaign_delivery_summaries: {
        Args: { payload: Json };
        Returns: Json;
      };
      get_campaign_delivery_statistics: {
        Args: { payload: Json };
        Returns: Json;
      };
      get_workspace_campaign_statistics: {
        Args: { payload: Json };
        Returns: Json;
      };
      list_campaign_delivery_tasks: { Args: { payload: Json }; Returns: Json };
      resolve_delivery_unknown: { Args: { payload: Json }; Returns: Json };
      worker_recover_expired_delivery_leases: {
        Args: Record<string, never>;
        Returns: number;
      };
      worker_claim_delivery_batch: { Args: { payload: Json }; Returns: Json };
      worker_complete_delivery_task: { Args: { payload: Json }; Returns: Json };
      worker_reconcile_delivery_events: {
        Args: { payload: Json };
        Returns: Json;
      };
      worker_cleanup_delivery_events: {
        Args: { payload: Json };
        Returns: Json;
      };
      resolve_public_unsubscribe: { Args: { payload: Json }; Returns: Json };
      apply_public_unsubscribe: { Args: { payload: Json }; Returns: Json };
      create_workspace_invitation: { Args: { payload: Json }; Returns: Json };
      resend_workspace_invitation: { Args: { payload: Json }; Returns: Json };
      revoke_workspace_invitation: { Args: { payload: Json }; Returns: Json };
      accept_workspace_invitation: { Args: { payload: Json }; Returns: Json };
      list_workspace_team: { Args: { payload: Json }; Returns: Json };
      get_workspace_invitation_preview: {
        Args: { payload: Json };
        Returns: Json;
      };
      change_workspace_member_role: { Args: { payload: Json }; Returns: Json };
      remove_workspace_member: { Args: { payload: Json }; Returns: Json };
      transfer_workspace_ownership: { Args: { payload: Json }; Returns: Json };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
